mata:

mata clear

files = ("2012/ACCOUNTABILITY_ACHIEVEMENT_GRADE.xlsx", 
"2012/ACCOUNTABILITY_ACHIEVEMENT_LEVEL.xlsx", 
"2012/ACCOUNTABILITY_ACHIEVEMENT_SUMMARY.xlsx", 
"2012/ACCOUNTABILITY_CCR_HIGHSCHOOL.xlsx", 
"2012/ACCOUNTABILITY_CCR_MIDDLESCHOOL.xlsx", 
"2012/ACCOUNTABILITY_FEDERAL_DATA.xlsx", 
"2012/ACCOUNTABILITY_GAP_LEVEL.xlsx", 
"2012/ACCOUNTABILITY_GAP_SUMMARY.xlsx", 
"2012/ACCOUNTABILITY_GRADUATION_RATE.xlsx", 
"2012/ACCOUNTABILITY_GROWTH.xlsx", 
"2012/ACCOUNTABILITY_PROFILE.xlsx", 
"2012/ACCOUNTABILITY_SUMMARY.xlsx", 
"2012/ASSESSMENT_ACT.xlsx", 
"2012/ASSESSMENT_EXPLORE.xlsx", 
"2012/ASSESSMENT_KPREP_EOC.xlsx", 
"2012/ASSESSMENT_KPREP_GRADE.xlsx", 
"2012/ASSESSMENT_KPREP_LEVEL.xlsx", 
"2012/ASSESSMENT_NAEP.xlsx", 
"2012/ASSESSMENT_NRT.xlsx", 
"2012/ASSESSMENT_PLAN.xlsx", 
"2012/DELIVERY_TARGET_CCR.xlsx", 
"2012/DELIVERY_TARGET_PROFICIENCY-GAP.xlsx", 
"2012/LEARNING_ENVIRONMENT_SAFETY.xlsx", 
"2012/LEARNING_ENVIRONMENT_STUDENTS-TEACHERS.xlsx", 
"2012/PROFILE.xlsx", 
"2013/ACCOUNTABILITY_ACHIEVEMENT_GRADE.xlsx", 
"2013/ACCOUNTABILITY_ACHIEVEMENT_LEVEL.xlsx", 
"2013/ACCOUNTABILITY_ACHIEVEMENT_SUMMARY.xlsx", 
"2013/ACCOUNTABILITY_CCR_HIGHSCHOOL.xlsx", 
"2013/ACCOUNTABILITY_CCR_MIDDLESCHOOL.xlsx", 
"2013/ACCOUNTABILITY_FEDERAL_DATA.xlsx", 
"2013/ACCOUNTABILITY_GAP_LEVEL.xlsx", 
"2013/ACCOUNTABILITY_GAP_SUMMARY.xlsx", 
"2013/ACCOUNTABILITY_GRADUATION_RATE_AFGR.xlsx", 
"2013/ACCOUNTABILITY_GRADUATION_RATE_COHORT.xlsx", 
"2013/ACCOUNTABILITY_GROWTH.xlsx", 
"2013/ACCOUNTABILITY_PROFILE.xlsx", 
"2013/ACCOUNTABILITY_SUMMARY.xlsx", 
"2013/ASSESSMENT_ACT.xlsx", 
"2013/ASSESSMENT_ADVANCE_PLACEMENT.xlsx", 
"2013/ASSESSMENT_EXPLORE.xlsx", 
"2013/ASSESSMENT_KPREP_EOC.xlsx", 
"2013/ASSESSMENT_KPREP_GRADE.xlsx", 
"2013/ASSESSMENT_KPREP_LEVEL.xlsx", 
"2013/ASSESSMENT_NAEP.xlsx", 
"2013/ASSESSMENT_NRT.xlsx", 
"2013/ASSESSMENT_PLAN.xlsx", 
"2013/DELIVERY_TARGET_CCR.xlsx", 
"2013/DELIVERY_TARGET_GRADUATION_RATE_COHORT.xlsx", 
"2013/DELIVERY_TARGET_PROFICIENCY-GAP.xlsx", 
"2013/LEARNING_ENVIRONMENT_CAREER_PATHWAYS.xlsx", 
"2013/LEARNING_ENVIRONMENT_PROGRAMS.xlsx", 
"2013/LEARNING_ENVIRONMENT_SAFETY.xlsx", 
"2013/LEARNING_ENVIRONMENT_STUDENTS-TEACHERS.xlsx", 
"2013/LEARNING_ENVIRONMENT_TEACHING_METHODS.xlsx", 
"2013/PROFILE.xlsx", 
"2014/ACCOUNTABILITY_ACHIEVEMENT_GRADE.xlsx", 
"2014/ACCOUNTABILITY_ACHIEVEMENT_LEVEL.xlsx", 
"2014/ACCOUNTABILITY_ACHIEVEMENT_SUMMARY.xlsx", 
"2014/ACCOUNTABILITY_CCR_HIGHSCHOOL.xlsx", 
"2014/ACCOUNTABILITY_CCR_MIDDLESCHOOL.xlsx", 
"2014/ACCOUNTABILITY_FEDERAL_DATA_ATTENDANCE.xlsx", 
"2014/ACCOUNTABILITY_FEDERAL_DATA_PARTICIPATION_RATE.xlsx", 
"2014/ACCOUNTABILITY_GAP_LEVEL.xlsx", 
"2014/ACCOUNTABILITY_GAP_SUMMARY.xlsx", 
"2014/ACCOUNTABILITY_GRADUATION_RATE_COHORT.xlsx", 
"2014/ACCOUNTABILITY_GROWTH.xlsx", 
"2014/ACCOUNTABILITY_PROFILE.xlsx", 
"2014/ACCOUNTABILITY_SUMMARY.xlsx", 
"2014/ASSESSMENT_ACT.xlsx", 
"2014/ASSESSMENT_ADVANCE_PLACEMENT.xlsx", 
"2014/ASSESSMENT_EXPLORE.xlsx", 
"2014/ASSESSMENT_KPREP_EOC.xlsx", 
"2014/ASSESSMENT_KPREP_GRADE.xlsx", 
"2014/ASSESSMENT_KPREP_LEVEL.xlsx", 
"2014/ASSESSMENT_KSCREEN.xlsx", 
"2014/ASSESSMENT_NAEP.xlsx", 
"2014/ASSESSMENT_NRT.xlsx", 
"2014/ASSESSMENT_PLAN.xlsx", 
"2014/CTE_CAREER_CCR.xlsx", 
"2014/CTE_CAREER_PATHWAYS.xlsx", 
"2014/CTE_CAREER_PERKINS.xlsx", 
"2014/DELIVERY_TARGET_CCR.xlsx", 
"2014/DELIVERY_TARGET_GRADUATION_RATE_COHORT.xlsx", 
"2014/DELIVERY_TARGET_KSCREEN.xlsx", 
"2014/DELIVERY_TARGET_PROFICIENCY-GAP.xlsx", 
"2014/DELIVERY_TARGET_PROGRAM_REVIEW.xlsx", 
"2014/FINANCE.xlsx", 
"2014/LEARNING_ENVIRONMENT_PROGRAMS.xlsx", 
"2014/LEARNING_ENVIRONMENT_SAFETY.xlsx", 
"2014/LEARNING_ENVIRONMENT_STUDENTS-TEACHERS.xlsx", 
"2014/LEARNING_ENVIRONMENT_TEACHING_METHODS.xlsx", 
"2014/PROFILE.xlsx", 
"2014/PROGRAM_REVIEW.xlsx", 
"2015/ACCOUNTABILITY_ACHIEVEMENT_GRADE.xlsx", 
"2015/ACCOUNTABILITY_ACHIEVEMENT_LEVEL.xlsx", 
"2015/ACCOUNTABILITY_ACHIEVEMENT_SUMMARY.xlsx", 
"2015/ACCOUNTABILITY_CCR_HIGHSCHOOL.xlsx", 
"2015/ACCOUNTABILITY_CCR_MIDDLESCHOOL.xlsx", 
"2015/ACCOUNTABILITY_FEDERAL_DATA_ATTENDANCE.xlsx", 
"2015/ACCOUNTABILITY_FEDERAL_DATA_PARTICIPATION_RATE.xlsx", 
"2015/ACCOUNTABILITY_GAP_LEVEL.xlsx", 
"2015/ACCOUNTABILITY_GAP_SUMMARY.xlsx", 
"2015/ACCOUNTABILITY_GROWTH.xlsx", 
"2015/ACCOUNTABILITY_PROFILE.xlsx", 
"2015/ACCOUNTABILITY_SUMMARY.xlsx", 
"2015/ASSESSMENT_ACT.xlsx", 
"2015/ASSESSMENT_ADVANCE_PLACEMENT.xlsx", 
"2015/ASSESSMENT_EXPLORE.xlsx", 
"2015/ASSESSMENT_KPREP_EOC.xlsx", 
"2015/ASSESSMENT_KPREP_GRADE.xlsx", 
"2015/ASSESSMENT_KPREP_LEVEL.xlsx", 
"2015/ASSESSMENT_KSCREEN.xlsx", 
"2015/ASSESSMENT_NAEP.xlsx", 
"2015/ASSESSMENT_NRT.xlsx", 
"2015/ASSESSMENT_PLAN.xlsx", 
"2015/CTE_CAREER_CCR.xlsx", 
"2015/CTE_CAREER_PATHWAYS.xlsx", 
"2015/CTE_CAREER_PERKINS.xlsx", 
"2015/DELIVERY_TARGET_CCR.xlsx", 
"2015/DELIVERY_TARGET_GRADUATION_RATE_COHORT.xlsx", 
"2015/DELIVERY_TARGET_KSCREEN.xlsx", 
"2015/DELIVERY_TARGET_PROFICIENCY_GAP.xlsx", 
"2015/DELIVERY_TARGET_PROGRAM_REVIEW.xlsx", 
"2015/FINANCE.xlsx", 
"2015/LEARNING_ENVIRONMENT_EQUITY.xlsx", 
"2015/LEARNING_ENVIRONMENT_PROGRAMS.xlsx", 
"2015/LEARNING_ENVIRONMENT_SAFETY.xlsx", 
"2015/LEARNING_ENVIRONMENT_STUDENTS-TEACHERS.xlsx", 
"2015/LEARNING_ENVIRONMENT_TEACHING_METHODS.xlsx", 
"2015/PROFILE.xlsx", 
"2015/PROGRAM_REVIEW.xlsx", 
"2016/PROFILE.xlsx")

xlfile = xl()
xlfile.set_mode("open")
row = 1
col = (1, 100)
data = J(200, 102, "")

for (i = 1; i <= cols(files); i++) {
	files[1, i]
	xlfile.load_book(files[1, i])
	sheets = xlfile.get_sheets()
	for (j = 1; j <= rows(sheets); j++) {
		if (sheets[j, 1] != "FILE LAYOUT" & sheets[j, 1] != "Sheet 2" & sheets[j, 1] != "Sheet 3") {
			xlfile.set_sheet(sheets[j, 1])
			data = (data \ (files[1, i], sheets[j, 1], xlfile.get_string(row, col)))
		}
	}	
	xlfile.close_book()
}		

rcfile = fopen("rcVariables.csv", "w")

for (i = 1; i <= rows(data); i++) {

	for (j = 1; j <= cols(data); j++) {
	
		fwrite(rcfile, data[i, j] + ";;")
	
	}
	
	fwrite(rcfile, char((10)))

}

fclose(rcfile)
	
end

import delimited using rcVariables.csv, delim(";;") varn(nonames) clear
drop if mi(v1)
forv i = 1/205 {
	if (mod(`i', 2) == 0) drop v`i'
}
drop v175-v205
qui: ds
loc vars `r(varlist)'
forv i = 1/`: word count `vars'' {
	rename (`: word `i' of `vars'')(v`i')
}
qui: split v1, gen(x) parse("/")
rename (v1 v2 x1 x2)(filename worksheet directory filenm)
order filename worksheet directory filenm
sort filenm directory
qui: drop in 1/4
cd ../
qui: drop if mi(v3)
qui: destring directory, replace
qui: bys filenm directory: g byte wrksheets = _N
order filename worksheet directory filenm wrksheets

export delimited using reportCardVariables.csv, delim(",") replace
